services:
  pgvector:
    image: 'pgvector/pgvector:pg16-trixie'
    environment:
      - 'POSTGRES_DB=Dev'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=postgres'

    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432'

# docker-compose up -d
# docker-compose down